### ISSUE TITLE
Test Tracker Required.

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#6532]
Test Tracker Required. 
https://drive.google.com/open?id=1dU4sBpXykhnEU00RcKxofZAaSu8Nf0ar

- [x] #12775
- [x] Add Entry during Billing
- [x] Add Entry During Barcode Printing
- [x] Add Entries During Sample Management Steps (Accept, Sent, Receive, Put to Analyser, etc)
- [x] Add ENtry during report management (data entry, approve, print, sms, etc)
- [x] Display History for selected test

**Comment by Irani96** [comment]
fixed

**Comment by damithdeshan98** [comment]
Fixed  #13284
